name: SolidityGuard CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  scan:
    name: Scan Smart Contracts with SolidityGuard
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run SolidityGuard scanner
      - name: Run SolidityGuard
        run: |
          echo "Scanning contracts for vulnerabilities..."
          python scanner/scanner.py scanner/examples/vulnerable_contract.sol

      # Step 5: Fail the build if vulnerabilities are detected
      - name: Check for vulnerabilities
        run: |
          OUTPUT=$(python scanner/scanner.py scanner/examples/vulnerable_contract.sol)
          echo "$OUTPUT"
          if echo "$OUTPUT" | grep -q "Security vulnerabilities detected"; then
            echo "Vulnerabilities found! Failing the build."
            exit 1
          fi
        shell: bash
